=== lmbt97/DAW_LMSGI_LluisBauza/Tasca_4_1_Lluis_Bauza/Exercici 1/XSD/cifp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://paucasesnovescifp.cat"
    xmlns="https://paucasesnovescifp.cat"
    elementFormDefault = "qualified">

    <xs:element name="cifp">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="alumne"/>
                <xs:element ref="professor"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="alumne">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nom"/>
                <xs:element ref="llinatges"/>
                <xs:element ref="data_naixement" minOccurs="0"/>
                <xs:element ref="correu" minOccurs="0"/>
                <xs:element ref="telefon" minOccurs="0"/>
                <xs:element ref="adress" minOccurs="0"/>
                <xs:element ref="data_matricula"/>
                <xs:element name="curs">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="DAM"/>
                            <xs:enumeration value="DAW"/>
                            <xs:enumeration value="ASIX"/>
                            <xs:enumeration value="SMX"/>
                            <xs:enumeration value="SEIA"/>
                            <xs:enumeration value="ER"/>
                            <xs:enumeration value="AUT"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>    
            </xs:sequence>

            <xs:attribute name="id" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="professor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nom"/>
                <xs:element ref="llinatges"/>
                <xs:element ref="data_naixement" minOccurs="0"/>
                <xs:element ref="correu" minOccurs="0"/>
                <xs:element ref="telefon" minOccurs="0"/>
                <xs:element ref="adress" minOccurs="0"/>
                <xs:element ref="data_incorporacio"/>
                <xs:element name="departament">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Informàtica"/>
                            <xs:enumeration value="Electricitat"/>
                            <xs:enumeration value="Automoció"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="assignatura" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom_assignatura">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="cicle" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="DAM"/>
                                                        <xs:enumeration value="DAW"/>
                                                        <xs:enumeration value="ASIX"/>
                                                        <xs:enumeration value="SMX"/>
                                                        <xs:enumeration value="SEIA"/>
                                                        <xs:enumeration value="ER"/>
                                                        <xs:enumeration value="AUT"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                    </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="data_inici" minOccurs="0"/>
                            <xs:element ref="data_final" minOccurs="0"/>
                        </xs:sequence>

                        <xs:attribute name="id_assignatura" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

            <xs:attribute name="id" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>


    <xs:element name="nom" type="xs:string"/>
    <xs:element name="llinatges" type="xs:string"/>
    <xs:element name="data_naixement" type="xs:string"/>
    <xs:element name="correu" type="xs:string"/>
    <xs:element name="telefon" type="xs:string"/>
    <xs:element name="adress" type="xs:string"/>
    <xs:element name="data_matricula" type="xs:string"/>
    <xs:element name="data_incorporacio" type="xs:string"/>
    <xs:element name="data_inici" type="xs:string"/>
    <xs:element name="data_final" type="xs:string"/>

</xs:schema>


<!--
para hacer nom_assignatura: https://www.w3schools.com/xml/el_simplecontent.asp
simpleContent y "extension", en este caso que tenemos un complexType porque tiene atributos
pero su contenido es simple. 
-->

=== lmbt97/DAW_LMSGI_LluisBauza/Tasca_4_1_Lluis_Bauza/Exercici 1/XSD/cifp.xml
<?xml version="1.0" encoding="UTF-8"?>

<cifp
xmlns="https://paucasesnovescifp.cat" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://paucasesnovescifp.cat cifp.xsd">
    <alumne id="001">
        <nom>Lluís</nom>
        <llinatges>Bauzá Togores</llinatges>
        <data_naixement>17 de gener del 1997</data_naixement>
        <correu>luismiguelbauza@paucasesnovescifp.cat</correu>
        <telefon>666666666</telefon>
        <adreça>Avinguda Alcudia, 1</adreça>
        <data_matricula>01 d'Octubre de 2025</data_matricula>
        <curs>DAW</curs>
    </alumne>
    <professor id="989">
        <nom>Walter Manuel</nom>
        <llinatges>Aguilar Pastor</llinatges>
        <correu>apw@paucasesnovescifp.cat</correu>
        <telefon>666666666</telefon>
        <data_incorporacio>01 de Setembre de 2023</data_incorporacio>
        <departament>Informàtica</departament>
        <assignatura id_assignatura="0373">
            <nom_assignatura cicle="DAW">Llenguatges de marques i sistemes de gestió de la informació</nom_assignatura>
            <data_inici>1 d'Octubre de 2025</data_inici>
        </assignatura>
                <assignatura id_assignatura="0484">
            <nom_assignatura cicle="DAW">Bases de Dades</nom_assignatura>
            <data_inici>1 d'Octubre de 2025</data_inici>
        </assignatura>
    </professor>
</cifp>
